<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Tests;

use Core\Types\CallbackCatcher;

class ClientFactory
{
    public static function create(
        CallbackCatcher $httpCallback
    ): \SwaggerPetstoreOpenAPI30Lib\SwaggerPetstoreOpenAPI30Client {
        $clientBuilder = \SwaggerPetstoreOpenAPI30Lib\SwaggerPetstoreOpenAPI30ClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(
        \SwaggerPetstoreOpenAPI30Lib\SwaggerPetstoreOpenAPI30ClientBuilder $builder
    ): \SwaggerPetstoreOpenAPI30Lib\SwaggerPetstoreOpenAPI30ClientBuilder {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(
        \SwaggerPetstoreOpenAPI30Lib\SwaggerPetstoreOpenAPI30ClientBuilder $builder
    ): \SwaggerPetstoreOpenAPI30Lib\SwaggerPetstoreOpenAPI30ClientBuilder {
        $timeout = getenv('SWAGGER_PETSTORE_OPEN_API_30_LIB_TIMEOUT');
        $numberOfRetries = getenv('SWAGGER_PETSTORE_OPEN_API_30_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('SWAGGER_PETSTORE_OPEN_API_30_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('SWAGGER_PETSTORE_OPEN_API_30_LIB_ENVIRONMENT');
        $apiKey = getenv('SWAGGER_PETSTORE_OPEN_API_30_LIB_API_KEY');

        if ($timeout !== false && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if ($numberOfRetries !== false && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if ($maximumRetryWaitTime !== false && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if ($environment !== false) {
            $builder->environment($environment);
        }

        if ($apiKey !== false) {
            $builder->apiKey($apiKey);
        }

        return $builder;
    }
}
