<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SwaggerPetstoreOpenAPI30Lib\Models\Tag;

/**
 * Builder for model Tag
 *
 * @see Tag
 */
class TagBuilder
{
    /**
     * @var Tag
     */
    private $instance;

    private function __construct(Tag $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new tag Builder object.
     */
    public static function init(): self
    {
        return new self(new Tag());
    }

    /**
     * Sets id field.
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new tag object.
     */
    public function build(): Tag
    {
        return CoreHelper::clone($this->instance);
    }
}
