<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Models;

use stdClass;
use SwaggerPetstoreOpenAPI30Lib\Utils\DateTimeHelper;

class Order implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $id;

    /**
     * @var int|null
     */
    private $petId;

    /**
     * @var int|null
     */
    private $quantity;

    /**
     * @var \DateTime|null
     */
    private $shipDate;

    /**
     * @var string|null
     */
    private $orderStatus = OrderStatusEnum::APPROVED;

    /**
     * @var bool|null
     */
    private $complete;

    /**
     * Returns Id.
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @maps id
     */
    public function setId(?int $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Pet Id.
     */
    public function getPetId(): ?int
    {
        return $this->petId;
    }

    /**
     * Sets Pet Id.
     *
     * @maps petId
     */
    public function setPetId(?int $petId): void
    {
        $this->petId = $petId;
    }

    /**
     * Returns Quantity.
     */
    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     *
     * @maps quantity
     */
    public function setQuantity(?int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Returns Ship Date.
     */
    public function getShipDate(): ?\DateTime
    {
        return $this->shipDate;
    }

    /**
     * Sets Ship Date.
     *
     * @maps shipDate
     * @factory \SwaggerPetstoreOpenAPI30Lib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setShipDate(?\DateTime $shipDate): void
    {
        $this->shipDate = $shipDate;
    }

    /**
     * Returns Order Status.
     * Order Status
     */
    public function getOrderStatus(): ?string
    {
        return $this->orderStatus;
    }

    /**
     * Sets Order Status.
     * Order Status
     *
     * @maps orderStatus
     * @factory \SwaggerPetstoreOpenAPI30Lib\Models\OrderStatusEnum::checkValue
     */
    public function setOrderStatus(?string $orderStatus): void
    {
        $this->orderStatus = $orderStatus;
    }

    /**
     * Returns Complete.
     */
    public function getComplete(): ?bool
    {
        return $this->complete;
    }

    /**
     * Sets Complete.
     *
     * @maps complete
     */
    public function setComplete(?bool $complete): void
    {
        $this->complete = $complete;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']          = $this->id;
        }
        if (isset($this->petId)) {
            $json['petId']       = $this->petId;
        }
        if (isset($this->quantity)) {
            $json['quantity']    = $this->quantity;
        }
        if (isset($this->shipDate)) {
            $json['shipDate']    = DateTimeHelper::toRfc3339DateTime($this->shipDate);
        }
        if (isset($this->orderStatus)) {
            $json['orderStatus'] = OrderStatusEnum::checkValue($this->orderStatus);
        }
        if (isset($this->complete)) {
            $json['complete']    = $this->complete;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
