<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib;

use Core\Authentication\CoreAuth;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class CustomHeaderAuthenticationManager extends CoreAuth implements CustomHeaderAuthenticationCredentials
{
    private $apiKey;

    /**
     * Returns an instance of this class.
     *
     * @param string $apiKey
     */
    public function __construct(string $apiKey)
    {
        parent::__construct(HeaderParam::init('api_key', $apiKey)->required());
        $this->apiKey = $apiKey;
    }

    /**
     * String value for apiKey.
     */
    public function getApiKey(): string
    {
        return $this->apiKey;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $apiKey
     */
    public function equals(string $apiKey): bool
    {
        return $apiKey == $this->apiKey;
    }
}
